#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Dec 22 10:08:47 +03 2025
# SW Build 5239630 on Fri Nov 08 22:34:34 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim system_top_eye_func_impl -key {Post-Implementation:sim_1:Functional:system_top_eye} -tclbatch system_top_eye.tcl -log simulate.log"
xsim system_top_eye_func_impl -key {Post-Implementation:sim_1:Functional:system_top_eye} -tclbatch system_top_eye.tcl -log simulate.log

